### ISSUE TITLE
Doubles at Routing section

### ISSUE THREAD

**Issue by egig** [codeguy/Slim-Documentation-Old#9]
I paste this from sidebar menu, Then I check the source and yes I found there are doubles

Route Parameters
Route Names
Route Parameters
Route Conditions
Route Names
Route Conditions
Route Middleware
Route Helpers
Route Middleware
Route URL Rewriting
Route Helpers
Route URL Rewriting

Just make sure, I can't find the differ of the each double, is it supposed to be like that?? Thanks.

**Comment by codeguy** [comment]
Solved in a separate commit. Thanks!
